export type { Database, Json, Tables, TablesInsert, TablesUpdate, Enums } from './database.types'
export { Constants } from './database.types'
export { supabaseEnv, supabaseEnvOptional, supabaseServiceEnv } from './env'
export { createBrowserSupabaseClient } from './browser'
export { createServerSupabaseClient } from './server'
export { createServiceSupabaseClient } from './admin'

export type ProfileRole = 'user' | 'admin'
export type ForumAdminInviteStatus = 'pending' | 'accepted' | 'declined' | 'cancelled'
export type NotificationType =
  | 'post_comment'
  | 'comment_reply'
  | 'post_upvote'
  | 'comment_upvote'
  | 'community_post'
  | 'forum_admin_invite'
  | 'forum_admin_invite_accepted'
  | 'forum_admin_invite_declined'
  | 'forum_admin_removed'
  | 'post_removed'
  | 'comment_removed'
  | 'community_kicked'
