'use client'

import { useEffect, useState } from 'react'
import { Sparkles, TriangleAlert } from 'lucide-react'

import { Badge } from '@/components/ui/badge'
import type { AiSummary, SummarySource } from '@/lib/ai/types'
import type { Comment, Post } from '@/lib/types'

interface AiSummaryCardProps {
  post: Post
  comments: Comment[]
}

interface SummaryResponse {
  summary: AiSummary
  source: SummarySource
  model: string
}

export function AiSummaryCard({ post, comments }: AiSummaryCardProps) {
  const [data, setData] = useState<SummaryResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  // Keyed on the comment count as well as the post: when the discussion moves,
  // the cached summary is stale and the route regenerates it.
  const commentCount = comments.length

  useEffect(() => {
    let cancelled = false

    setLoading(true)
    setError(null)

    fetch(`/api/posts/${post.id}/summary`)
      .then(async (res) => {
        if (!res.ok) throw new Error(`Request failed (${res.status})`)
        return (await res.json()) as SummaryResponse
      })
      .then((payload) => {
        if (!cancelled) setData(payload)
      })
      .catch((err: Error) => {
        if (!cancelled) setError(err.message)
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })

    return () => {
      cancelled = true
    }
  }, [post.id, commentCount])

  const byModel = data?.source === 'model' || data?.source === 'cache'

  return (
    <div className="rounded-xl border border-primary/25 bg-primary/5 p-4">
      <div className="mb-3 flex items-center gap-2">
        <span className="flex size-6 items-center justify-center rounded-full bg-primary text-primary-foreground">
          <Sparkles className="size-3.5" />
        </span>
        <h3 className="font-heading text-sm font-semibold text-foreground">
          {/* Never claim AI for a summary no model produced. */}
          {loading ? 'Summarizing…' : byModel ? 'AI Topic Summary' : 'Thread Summary'}
        </h3>
        {data && (
          <Badge variant="secondary" className="ml-auto">
            {data.summary.sentiment}
          </Badge>
        )}
      </div>

      {loading ? (
        <div className="space-y-2" aria-live="polite" aria-busy="true">
          <div className="h-3 w-11/12 animate-pulse rounded bg-primary/15" />
          <div className="h-3 w-4/5 animate-pulse rounded bg-primary/15" />
          <div className="h-3 w-3/5 animate-pulse rounded bg-primary/15" />
          <p className="pt-1 text-xs text-muted-foreground">
            Reading this thread and {commentCount} comment
            {commentCount === 1 ? '' : 's'}…
          </p>
        </div>
      ) : error ? (
        <p className="flex items-start gap-2 text-sm text-muted-foreground">
          <TriangleAlert className="mt-0.5 size-4 shrink-0 text-destructive" />
          Could not build a summary for this thread. {error}
        </p>
      ) : data ? (
        <div className="space-y-3 text-sm">
          <p className="leading-relaxed text-foreground">{data.summary.tldr}</p>

          <div>
            <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Key points
            </p>
            <ul className="space-y-1.5">
              {data.summary.keyPoints.map((point, i) => (
                <li key={i} className="flex gap-2 leading-relaxed">
                  <span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" />
                  <span className="text-foreground/90">{point}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="rounded-lg bg-background/70 p-2.5">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Consensus
            </p>
            <p className="mt-1 leading-relaxed text-foreground/90">
              {data.summary.consensus}
            </p>
          </div>

          <p className="text-[0.7rem] text-muted-foreground">
            {byModel
              ? `Generated by ${data.model} · may not be perfect`
              : 'Rule-based summary — sign in to generate an AI summary'}
          </p>
        </div>
      ) : null}
    </div>
  )
}
