import type { Comment, Community, Post } from './types'

const HOUR = 1000 * 60 * 60
const DAY = HOUR * 24
const now = Date.now()

export const CURRENT_USER = 'u/thiha_dev'

const COMMON_RULES = [
  'Be respectful. No harassment, hate speech, or personal attacks.',
  'Stay on topic and keep posts relevant to MTU students.',
  'No spam, self-promotion, or reselling of academic material.',
  'Cite sources when sharing notes, papers, or study material.',
]

export const communities: Community[] = [
  {
    id: 'c-eee',
    slug: 'm/EEE',
    name: 'Electrical Engineering',
    description:
      'Circuits, power systems, embedded design and everything EE at MTU.',
    members: 4820,
    colorClass: 'bg-chart-2 text-white',
    tags: ['engineering', 'hardware'],
    online: 214,
    foundedAt: now - 1180 * DAY,
    moderators: ['u/zaw_htet', 'u/su_latt'],
    rules: [
      ...COMMON_RULES,
      'Use the Help flair for circuit troubleshooting and include a schematic.',
    ],
  },
  {
    id: 'c-it',
    slug: 'm/IT',
    name: 'Information Technology',
    description: 'Software, algorithms, web, AI and IT coursework discussions.',
    members: 6310,
    colorClass: 'bg-primary text-primary-foreground',
    tags: ['software', 'ai', 'programming'],
    online: 389,
    foundedAt: now - 1320 * DAY,
    moderators: ['u/thiha_dev', 'u/aung_min'],
    rules: [
      ...COMMON_RULES,
      'Wrap code in code blocks and mention your language/framework.',
    ],
  },
  {
    id: 'c-mech',
    slug: 'm/Mech',
    name: 'Mechanical Engineering',
    description: 'Thermodynamics, CAD, manufacturing and robotics.',
    members: 3990,
    colorClass: 'bg-chart-5 text-white',
    tags: ['engineering', 'robotics'],
    online: 156,
    foundedAt: now - 1090 * DAY,
    moderators: ['u/nyein_chan'],
    rules: [
      ...COMMON_RULES,
      'Share CAD files responsibly and respect project ownership.',
    ],
  },
  {
    id: 'c-civil',
    slug: 'm/Civil',
    name: 'Civil Engineering',
    description: 'Structures, surveying, materials and construction projects.',
    members: 3120,
    colorClass: 'bg-chart-4 text-white',
    tags: ['engineering', 'construction'],
    online: 98,
    foundedAt: now - 1010 * DAY,
    moderators: ['u/htet_aung'],
    rules: [
      ...COMMON_RULES,
      'Site photos must not expose private or restricted locations.',
    ],
  },
  {
    id: 'c-campus',
    slug: 'm/CampusLife',
    name: 'Campus Life',
    description: 'Events, clubs, hostels, canteen reviews and student life.',
    members: 8740,
    colorClass: 'bg-success text-white',
    tags: ['social', 'events'],
    online: 512,
    foundedAt: now - 1400 * DAY,
    moderators: ['u/khin_thidar', 'u/may_phyu'],
    rules: [
      ...COMMON_RULES,
      'Event posts must include date, venue, and how to join.',
    ],
  },
  {
    id: 'c-exams',
    slug: 'm/Exams',
    name: 'Exams & Resources',
    description: 'Past papers, study guides, notes and exam schedules.',
    members: 7150,
    colorClass: 'bg-downvote text-white',
    tags: ['academics', 'resources'],
    online: 431,
    foundedAt: now - 1260 * DAY,
    moderators: ['u/su_latt', 'u/may_phyu'],
    rules: [
      ...COMMON_RULES,
      'Label the year and subject clearly when sharing past papers.',
    ],
  },
  {
    id: 'c-music',
    slug: 'm/MusicClub',
    name: 'Music Club',
    description:
      'Jam sessions, band practice, gig announcements and gear talk for MTU musicians.',
    members: 2640,
    colorClass: 'bg-chart-3 text-white',
    tags: ['club', 'music', 'arts'],
    online: 173,
    foundedAt: now - 860 * DAY,
    moderators: ['u/may_phyu', 'u/khin_thidar'],
    rules: [
      ...COMMON_RULES,
      'Tag original compositions and covers clearly, and credit collaborators.',
    ],
  },
  {
    id: 'c-scitech',
    slug: 'm/SciTechClub',
    name: 'Science & Technology Club',
    description:
      'Hackathons, maker projects, research showcases and STEM competitions across MTU.',
    members: 4180,
    colorClass: 'bg-chart-1 text-primary-foreground',
    tags: ['club', 'stem', 'projects'],
    online: 268,
    foundedAt: now - 940 * DAY,
    moderators: ['u/thiha_dev', 'u/nyein_chan'],
    rules: [
      ...COMMON_RULES,
      'Project posts should include goals, stack, and how others can contribute.',
    ],
  },
  {
    id: 'c-photo',
    slug: 'm/PhotographyClub',
    name: 'Photography Club',
    description:
      'Photo walks, campus shots, editing tips and monthly themed challenges.',
    members: 1990,
    colorClass: 'bg-chart-5 text-white',
    tags: ['club', 'photography', 'arts'],
    online: 121,
    foundedAt: now - 720 * DAY,
    moderators: ['u/su_latt'],
    rules: [
      ...COMMON_RULES,
      'Only post your own photos and respect the privacy of people in your shots.',
    ],
  },
  {
    id: 'c-sports',
    slug: 'm/SportsClub',
    name: 'Sports Club',
    description:
      'Football, basketball, tournaments, fitness and inter-department matches.',
    members: 5240,
    colorClass: 'bg-success text-white',
    tags: ['club', 'sports', 'fitness'],
    online: 302,
    foundedAt: now - 1150 * DAY,
    moderators: ['u/htet_aung', 'u/zaw_htet'],
    rules: [
      ...COMMON_RULES,
      'Match posts must include date, venue, and team or department.',
    ],
  },
  {
    id: 'c-debate',
    slug: 'm/DebateClub',
    name: 'Debate & Literary Club',
    description:
      'Debates, public speaking, creative writing and English practice sessions.',
    members: 1760,
    colorClass: 'bg-chart-4 text-white',
    tags: ['club', 'debate', 'writing'],
    online: 88,
    foundedAt: now - 680 * DAY,
    moderators: ['u/aung_min'],
    rules: [
      ...COMMON_RULES,
      'Keep arguments civil — critique ideas, not people.',
    ],
  },
]

export const posts: Post[] = [
  {
    id: 'p1',
    communityId: 'c-it',
    author: 'u/aung_min',
    title: 'Best roadmap to learn AI/ML as an MTU IT student in 2026?',
    body: 'I keep bouncing between courses and YouTube playlists. Should I start with math (linear algebra + probability) first, or jump straight into building projects with PyTorch? Also is the university GPU lab open for final year students only? Would love a structured path that fits alongside our normal coursework.',
    flair: 'Discussion',
    score: 342,
    commentCount: 4,
    createdAt: now - 3 * HOUR,
  },
  {
    id: 'p2',
    communityId: 'c-exams',
    author: 'u/su_latt',
    title: 'Compiled: All EE past papers (2018-2025) in one Drive folder',
    body: 'Spent the weekend scanning and organizing every Electrical Engineering final paper I could find from seniors. Sorted by year and subject, with a few marking schemes included. Drop a comment if a specific subject is missing and I will try to add it.',
    flair: 'Resource',
    score: 918,
    commentCount: 3,
    createdAt: now - 9 * HOUR,
  },
  {
    id: 'p3',
    communityId: 'c-campus',
    author: 'u/khin_thidar',
    title: 'Robotics Club is hosting a line-follower competition next month',
    body: 'Registration is open for all years. Teams of up to 3. Prizes for top 3 plus components sponsorship. We will run two practice sessions in the mechatronics lab. Comment if you want to join and I can add you to the group.',
    flair: 'Event',
    score: 205,
    commentCount: 2,
    createdAt: now - 5 * HOUR,
  },
  {
    id: 'p4',
    communityId: 'c-eee',
    author: 'u/zaw_htet',
    title: 'Why does my op-amp circuit oscillate at high gain? (schematic inside)',
    body: 'Building a non-inverting amplifier with gain around 100. At lower gain it is stable, but past ~50x it starts oscillating around 2MHz. I suspect stray capacitance or a bandwidth issue with the 741. Should I add a compensation cap or switch to a faster op-amp? Details and layout photo below.',
    flair: 'Help',
    score: 156,
    commentCount: 3,
    createdAt: now - 1 * HOUR,
  },
  {
    id: 'p5',
    communityId: 'c-mech',
    author: 'u/nyein_chan',
    title: 'CAD tip: parametric modeling saved my final year project',
    body: 'For anyone doing design projects, invest time in setting up parameters and constraints properly in SolidWorks/Fusion. When my supervisor asked for dimension changes the day before submission, I updated 3 variables instead of re-drawing everything. Sharing my template.',
    flair: 'Guide',
    score: 274,
    commentCount: 2,
    createdAt: now - 20 * HOUR,
  },
  {
    id: 'p6',
    communityId: 'c-it',
    author: 'u/thiha_dev',
    title: 'Made a small app to track hostel mess menu — open source',
    body: 'Got tired of walking to the canteen only to find the same dish. Built a tiny Next.js app where the mess staff can post the daily menu and students get notified. Code is on GitHub. Looking for contributors, especially for a Burmese language toggle.',
    flair: 'Project',
    score: 431,
    commentCount: 2,
    createdAt: now - 14 * HOUR,
  },
  {
    id: 'p7',
    communityId: 'c-civil',
    author: 'u/htet_aung',
    title: 'Field trip to the Yadanabon bridge — structural inspection notes',
    body: 'Our structures lecturer arranged a visit to study the bridge design and load distribution. Sharing my notes on the cable-stayed layout and the expansion joints. Great real-world complement to the theory we covered on tension members.',
    flair: 'Discussion',
    score: 189,
    commentCount: 1,
    createdAt: now - 30 * HOUR,
  },
  {
    id: 'p8',
    communityId: 'c-exams',
    author: 'u/may_phyu',
    title: 'Study group forming for Signals & Systems final — join us',
    body: 'We meet twice a week in the library, focusing on Fourier and Laplace problem sets. Currently 5 people, room for a few more. We split topics and teach each other. Comment your subject strengths so we can balance the group.',
    flair: 'Study Group',
    score: 97,
    commentCount: 1,
    createdAt: now - 2 * HOUR,
  },
  {
    id: 'p9',
    communityId: 'c-music',
    author: 'u/may_phyu',
    title: 'Open mic night this Friday at the student center — sign-up inside',
    body: 'Music Club is hosting our monthly open mic. Solo acts, bands, and acoustic sets all welcome. We have a PA, two mics, and a keyboard on site — bring your own guitar. Comment your act and rough set length so we can build the running order.',
    flair: 'Event',
    score: 168,
    commentCount: 2,
    createdAt: now - 4 * HOUR,
  },
  {
    id: 'p10',
    communityId: 'c-scitech',
    author: 'u/thiha_dev',
    title: '48-hour campus hackathon — teams forming now',
    body: 'Sci & Tech Club is running an overnight hackathon next weekend. Theme is "smarter campus". Prizes for top 3 plus a mentorship slot with alumni. Teams of 2-4. Comment your skills (frontend, hardware, ML, design) and we will help match teams.',
    flair: 'Event',
    score: 289,
    commentCount: 2,
    createdAt: now - 7 * HOUR,
  },
  {
    id: 'p11',
    communityId: 'c-photo',
    author: 'u/su_latt',
    title: 'This month theme: "Campus at Golden Hour" — share your shots',
    body: 'Our monthly challenge is live. Shoot anything on campus during sunrise or sunset. Top 3 by community votes get featured on the club board. Please post straight-out-of-camera or note your edits. Excited to see the library at dusk again.',
    flair: 'Challenge',
    score: 142,
    commentCount: 1,
    createdAt: now - 11 * HOUR,
  },
  {
    id: 'p12',
    communityId: 'c-sports',
    author: 'u/htet_aung',
    title: 'Inter-department football tournament bracket is out',
    body: 'The knockout bracket for the semester tournament is finalized. First matches are this Saturday on the main ground. EEE vs Civil kicks off at 9am. Full schedule in comments — come support your department and bring water, it will be hot.',
    flair: 'Announcement',
    score: 231,
    commentCount: 2,
    createdAt: now - 6 * HOUR,
  },
  {
    id: 'p13',
    communityId: 'c-debate',
    author: 'u/aung_min',
    title: 'Motion for this week: "AI does more good than harm for students"',
    body: 'Debate Club meets Thursday evening in the seminar room. This week we argue AI in education. Sign up for government or opposition in the comments. Beginners welcome — we pair new speakers with experienced ones for practice rounds.',
    flair: 'Discussion',
    score: 114,
    commentCount: 1,
    createdAt: now - 9 * HOUR,
  },
]

export const comments: Comment[] = [
  {
    id: 'cm1',
    postId: 'p1',
    parentId: null,
    author: 'u/su_latt',
    body: 'Do the math foundations in parallel, not before. Spend 60% building projects and 40% filling math gaps as you hit them. You retain far more that way.',
    score: 88,
    createdAt: now - 2.5 * HOUR,
  },
  {
    id: 'cm2',
    postId: 'p1',
    parentId: 'cm1',
    author: 'u/aung_min',
    body: 'That makes sense. Any specific first project you would recommend that is not just MNIST?',
    score: 21,
    createdAt: now - 2.2 * HOUR,
  },
  {
    id: 'cm3',
    postId: 'p1',
    parentId: 'cm2',
    author: 'u/nyein_chan',
    body: 'Build something that uses campus data — a timetable clash detector or a past-paper search engine. Real data keeps you motivated.',
    score: 34,
    createdAt: now - 2 * HOUR,
  },
  {
    id: 'cm4',
    postId: 'p1',
    parentId: null,
    author: 'u/khin_thidar',
    body: 'The GPU lab is open to 3rd and 4th years with a supervisor sign-off. Email the IT department head to get added to the access list.',
    score: 45,
    createdAt: now - 1.8 * HOUR,
  },
  {
    id: 'cm5',
    postId: 'p2',
    parentId: null,
    author: 'u/zaw_htet',
    body: 'This is incredible, thank you. Could you add Power Systems II from 2021? It is missing from the folder.',
    score: 40,
    createdAt: now - 8 * HOUR,
  },
  {
    id: 'cm6',
    postId: 'p2',
    parentId: 'cm5',
    author: 'u/su_latt',
    body: 'Added it just now along with the 2020 version. Refresh the folder.',
    score: 52,
    createdAt: now - 7.5 * HOUR,
  },
  {
    id: 'cm7',
    postId: 'p2',
    parentId: null,
    author: 'u/may_phyu',
    body: 'Pinning this in our study group. Seniors like you make this place better.',
    score: 30,
    createdAt: now - 6 * HOUR,
  },
  {
    id: 'cm8',
    postId: 'p3',
    parentId: null,
    author: 'u/thiha_dev',
    body: 'Count me in. I can help with the microcontroller firmware side.',
    score: 18,
    createdAt: now - 4.5 * HOUR,
  },
  {
    id: 'cm9',
    postId: 'p3',
    parentId: null,
    author: 'u/htet_aung',
    body: 'Is there a weight limit on the chassis? Planning our design around it.',
    score: 12,
    createdAt: now - 4 * HOUR,
  },
  {
    id: 'cm10',
    postId: 'p4',
    parentId: null,
    author: 'u/nyein_chan',
    body: 'The 741 is way too slow and its layout is picky. At 2MHz oscillation you are almost certainly seeing feedback instability. Add a small compensation cap (a few pF) across the feedback resistor first.',
    score: 61,
    createdAt: now - 0.8 * HOUR,
  },
  {
    id: 'cm11',
    postId: 'p4',
    parentId: 'cm10',
    author: 'u/zaw_htet',
    body: 'Tried 5pF and the oscillation stopped but gain dropped slightly. Acceptable tradeoff?',
    score: 15,
    createdAt: now - 0.6 * HOUR,
  },
  {
    id: 'cm12',
    postId: 'p4',
    parentId: null,
    author: 'u/aung_min',
    body: 'Also keep your feedback loop physically short and add a ground plane. Stray capacitance on a breadboard causes exactly this.',
    score: 28,
    createdAt: now - 0.5 * HOUR,
  },
  {
    id: 'cm13',
    postId: 'p5',
    parentId: null,
    author: 'u/htet_aung',
    body: 'Constraints are underrated. Also name your sketches and features — future you will thank present you.',
    score: 22,
    createdAt: now - 18 * HOUR,
  },
  {
    id: 'cm14',
    postId: 'p5',
    parentId: null,
    author: 'u/khin_thidar',
    body: 'Would love the template. Does it include a title block for our department format?',
    score: 9,
    createdAt: now - 16 * HOUR,
  },
  {
    id: 'cm15',
    postId: 'p6',
    parentId: null,
    author: 'u/may_phyu',
    body: 'This is genuinely useful. I can help with the Burmese translation toggle, DM me the repo.',
    score: 26,
    createdAt: now - 13 * HOUR,
  },
  {
    id: 'cm16',
    postId: 'p6',
    parentId: 'cm15',
    author: 'u/thiha_dev',
    body: 'Amazing, added you as a collaborator. Localization files are in /locales.',
    score: 14,
    createdAt: now - 12 * HOUR,
  },
  {
    id: 'cm17',
    postId: 'p7',
    parentId: null,
    author: 'u/nyein_chan',
    body: 'Cable-stayed vs suspension is such a good comparison to see in person. Thanks for the notes.',
    score: 11,
    createdAt: now - 28 * HOUR,
  },
  {
    id: 'cm18',
    postId: 'p8',
    parentId: null,
    author: 'u/aung_min',
    body: 'Strong on Laplace, weak on Z-transform. Happy to trade.',
    score: 7,
    createdAt: now - 1.5 * HOUR,
  },
  {
    id: 'cm19',
    postId: 'p9',
    parentId: null,
    author: 'u/khin_thidar',
    body: 'Putting my name down for a 10-minute acoustic set. Can I borrow a capo on the night?',
    score: 19,
    createdAt: now - 3.5 * HOUR,
  },
  {
    id: 'cm20',
    postId: 'p9',
    parentId: 'cm19',
    author: 'u/may_phyu',
    body: 'Added you to the list. Yes, we will have a couple of capos at the desk.',
    score: 11,
    createdAt: now - 3.2 * HOUR,
  },
  {
    id: 'cm21',
    postId: 'p10',
    parentId: null,
    author: 'u/nyein_chan',
    body: 'In for hardware and a bit of embedded. Would love a frontend teammate to pair with.',
    score: 24,
    createdAt: now - 6.5 * HOUR,
  },
  {
    id: 'cm22',
    postId: 'p10',
    parentId: 'cm21',
    author: 'u/thiha_dev',
    body: 'I can cover frontend and design. Let us form a team — I will DM you.',
    score: 17,
    createdAt: now - 6 * HOUR,
  },
  {
    id: 'cm23',
    postId: 'p11',
    parentId: null,
    author: 'u/zaw_htet',
    body: 'Got a great shot of the workshop building with the sun behind it last week. Posting tonight.',
    score: 13,
    createdAt: now - 10 * HOUR,
  },
  {
    id: 'cm24',
    postId: 'p12',
    parentId: null,
    author: 'u/zaw_htet',
    body: 'EEE squad ready. Can we get the full schedule pinned so we can plan practice?',
    score: 16,
    createdAt: now - 5.5 * HOUR,
  },
  {
    id: 'cm25',
    postId: 'p12',
    parentId: 'cm24',
    author: 'u/htet_aung',
    body: 'Pinned it. Group stage runs Saturday and Sunday, semis next week.',
    score: 10,
    createdAt: now - 5 * HOUR,
  },
  {
    id: 'cm26',
    postId: 'p13',
    parentId: null,
    author: 'u/su_latt',
    body: 'Sign me up for opposition. Good practice before the regional competition.',
    score: 8,
    createdAt: now - 8.5 * HOUR,
  },
]
